# Build stage
FROM golang:1.22 AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o /bin/store-service ./main.go

# Final stage
FROM golang:1.22
WORKDIR /app
COPY --from=builder /bin/store-service /app/store-service
COPY --from=builder /app/config.yaml /app/config.yaml
COPY --from=builder /app/internal/migrations /app/migrations
COPY --from=builder /app/internal/keys /app/keys

CMD ["/app/store-service"]
