package loadtestdata

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/google/uuid"
	"github.com/idlab-discover/kebeng/common/cerror"
	"github.com/idlab-discover/kebeng/services/gateway/internal/util"
	"github.com/idlab-discover/kebeng/services/gateway/load_test_data/model"
	"github.com/sirupsen/logrus"
	"github.com/snapcore/snapd/asserts"
)

type testHandler struct {
	util.BaseHandler
}

type TestAccountData struct {
	Accounts []model.TestAccount `json:"accounts"`
	Keys     []model.TestKey     `json:"keys"`
	SSHKeys  []model.TestSSHKey  `json:"ssh_keys"`
}

type TestStoreData struct {
	Entries []model.TestSnapEntry `json:"snap_entries"`
}

// LoadTestData creates a set of test data by calling the client methods
// of the Account, Store, and Assertion services via the gateway.
func CreateTestData(baseHandler *util.BaseHandler) error {
	// Initialize the test handler
	h := &testHandler{
		BaseHandler: *baseHandler,
	}
	// Load test data from JSON files
	accountTestData, err := h.loadInAccountTestData()
	if err != nil {
		logrus.Errorf("Failed to load account test data: %v", err)
		return fmt.Errorf("failed to load account test data: %v", err)
	}
	storeTestData, err := h.loadInStoreTestData()
	if err != nil {
		logrus.Errorf("Failed to load store test data: %v", err)
		return fmt.Errorf("failed to load store test data: %v", err)
	}

	logrus.Infof("Loaded all the test data successfully.")

	// create maps so that id's can be mapped to correct actual id that is generated by db
	// since these are actual UUID's they should be unique so they don't overwrite each other
	accountIDMap := make(map[string]string)
	storeIDMap := make(map[string]string)
	assertionIDMap := make(map[string]string)

	// Load the test data into the database
	ctx := context.Background()

	err = h.loadInAccountDataInDB(ctx, accountTestData, accountIDMap, assertionIDMap)
	if err != nil {
		logrus.Errorf("Failed to load account data into DB: %v", err)
		return fmt.Errorf("failed to load account data into DB: %v", err)
	}

	err = h.loadInStoreDataInDB(ctx, storeTestData, storeIDMap, accountIDMap)
	if err != nil {
		logrus.Errorf("Failed to load store data into DB: %v", err)
		return fmt.Errorf("failed to load store data into DB: %v", err)
	}
	logrus.Infof("Loaded all the test data into the database successfully.")

	return nil
}

// #################### HELPERS ####################

// ################# LOAD TEST DATA ####################

func (h *testHandler) loadInAccountTestData() (*TestAccountData, error) {
	filePath := h.Config.TestDataFolderPath + "/account_data.json"
	// check if file exists
	if _, err := os.Stat(filePath); os.IsNotExist(err) {
		logrus.Errorf("Test data file does not exist: %s", filePath)
		return nil, fmt.Errorf("test data file does not exist: %s", filePath)
	}
	file, err := os.ReadFile(filePath)
	if err != nil {
		return nil, fmt.Errorf("failed to open test data file: %v", err)
	}
	// Load the test data from the JSON file
	storeTestData := &TestAccountData{}
	err = json.Unmarshal(file, storeTestData)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal test data: %v", err)
	}
	return storeTestData, nil
}

func (h *testHandler) loadInStoreTestData() (*TestStoreData, error) {
	filePath := h.Config.TestDataFolderPath + "/store_data.json"
	// check if file exists
	if _, err := os.Stat(filePath); os.IsNotExist(err) {
		logrus.Errorf("Test data file does not exist: %s", filePath)
		return nil, fmt.Errorf("test data file does not exist: %s", filePath)
	}
	file, err := os.ReadFile(filePath)
	if err != nil {
		return nil, fmt.Errorf("failed to open test data file: %v", err)
	}
	// Load the test data from the JSON file
	storeTestData := &TestStoreData{}
	err = json.Unmarshal(file, storeTestData)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal test data: %v", err)
	}
	return storeTestData, nil
}

//  ################# INSERT TEST DATA IN DB ####################

func (h *testHandler) loadInAccountDataInDB(_ context.Context, accountTestData *TestAccountData, accountIDMap map[string]string, assertionIDMap map[string]string) error {
	// Create the accounts
	for _, account := range accountTestData.Accounts {
		accountResp := h.AccountClient.AddAccount(account.DisplayName, account.Username, account.Email, account.HashedPassword)
		if len(accountResp.Errors) > 0 {
			return fmt.Errorf("failed to create account: %v", accountResp.Errors)
		}
		// Store the account ID in the map
		h.saveID(accountIDMap, account.ID, accountResp.Id)
	}

	// Create the keys
	for _, key := range accountTestData.Keys {
		accId, err := h.getID(accountIDMap, key.AccountID)
		if err != nil {
			return fmt.Errorf("failed to get account ID: %v", err)
		}

		// Create the key
		priv, err := asserts.GenerateKey()
		if err != nil {
			return fmt.Errorf("failed to generate key: %v", err)
		}
		wire, err := asserts.EncodePublicKey(priv.PublicKey())
		if err != nil {
			return fmt.Errorf("failed to encode public key: %v", err)
		}
		fp := priv.PublicKey().ID()
		b64 := base64.StdEncoding.EncodeToString(wire)

		key.SHA3384 = fp
		key.EncodedPublicKey = b64

		keyResp := h.AccountClient.AddKey(key.AccountEmail, key.Name, key.SHA3384, key.EncodedPublicKey)
		if len(keyResp.Errors) > 0 {
			return fmt.Errorf("failed to create key: %v", keyResp.Errors)
		}
		// Store the key ID in the map
		h.saveID(accountIDMap, key.ID, keyResp.Id)

		since := time.Now()
		until := time.Now().Add(365 * 24 * time.Hour)

		accountKeyAssertResponse := h.AssertionClient.AddAccountKeyAssertion(key.EncodedPublicKey, key.SHA3384, accId.String(), key.Name, &since, &until)
		if len(accountKeyAssertResponse.Errors) > 0 {
			return fmt.Errorf("failed to create account key assertion: %v", accountKeyAssertResponse.Errors)
		}
		// Store the assertion ID in the map
		h.saveID(assertionIDMap, key.ID, accountKeyAssertResponse.Id)
	}

	// Create the SSH keys
	// not yet really implemented not sure what SSH Keys are used for still from repo we forked from
	// think it was for authentication or something?

	return nil
}

func (h *testHandler) loadInStoreDataInDB(ctx context.Context, storeTestData *TestStoreData, storeIDMap map[string]string, accountIDMap map[string]string) error {
	// --- Insert Entries ---
	for _, entry := range storeTestData.Entries {
		el := cerror.NewErrorList()

		accID, err := h.getID(accountIDMap, entry.AccountID)
		if err != nil {
			return fmt.Errorf("failed to get account ID: %v", err)
		}
		// dry run on false to actually insert
		registerSnapResp := h.StoreClient.RegisterSnapName(entry.Name, entry.Private, entry.Store, false, accID)
		if len(registerSnapResp.Errors) > 0 {
			return fmt.Errorf("failed to register snap name: %v", registerSnapResp.Errors)
		}
		h.saveID(storeIDMap, entry.ID, registerSnapResp.GetId())

		// UnscannedUpload with minio file
		snapFilePath := filepath.Join(h.Config.TestDataFolderPath, "minio", entry.Name+".snap")
		fileInfo, err := os.Stat(snapFilePath)
		if err != nil {
			return fmt.Errorf("failed to get file info: %v", err)
		}
		fileReader, err := os.Open(snapFilePath)
		if err != nil {
			return fmt.Errorf("failed to open snap file: %v", err)
		}
		uploadResp := h.StoreClient.UnscannedUpload(ctx, fileReader)
		if len(uploadResp.Errors) > 0 {
			fileReader.Close() // ensure the file is closed on error
			return fmt.Errorf("failed to upload snap file: %+v", uploadResp.Errors)
		}
		fileReader.Close()

		snapEntryId, err := h.getID(storeIDMap, entry.ID)
		if err != nil {
			return fmt.Errorf("failed to get snap entry ID: %v", err)
		}

		addUploadResp := h.StoreClient.AddUpload(entry.Name, snapEntryId, "processed", accID, uploadResp.GetTempFileName())
		if len(addUploadResp.Errors) > 0 {
			return fmt.Errorf("failed to add upload: %v", addUploadResp.Errors)
		}

		// to get SHA3_384 of uploaded file
		metadata := h.StoreClient.GetObjectCustomMetadata("unscanned", uploadResp.GetTempFileName())
		if len(metadata.Errors) > 0 {
			return fmt.Errorf("failed to get object metadata: %v", metadata.Errors)
		}
		
		// creates revision
		revisionResp := h.StoreClient.AddRevision(entry.Name, metadata.GetSha3_384(), uint64(fileInfo.Size()), []string{"amd64"}, []string{"latest", "1.0"}, uploadResp.GetTempFileName())
		if len(revisionResp.Errors) > 0 {
			return fmt.Errorf("failed to add revision: %v", revisionResp.Errors)
		}
		now := time.Now()
		revisionAssertionRespo := h.AssertionClient.AddSnapRevisionAssertion(metadata.GetSha3_384(), accID.String(), snapEntryId.String(), uint32(revisionResp.Revision), uint64(fileInfo.Size()), &now)
		if len(revisionAssertionRespo.Errors) > 0 {
			return fmt.Errorf("failed to add revision assertion: %v", revisionAssertionRespo.Errors)
		}

		// status op processed zetten
		uploadStatus := h.StoreClient.UpdateUploadStatus(addUploadResp.Id, "processed", revisionResp.Revision, el)
		if len(uploadStatus.Errors) > 0 {
			return fmt.Errorf("failed to update upload status: %v", uploadStatus.Errors)
		}
	}

	return nil
}

// ################## UTIL HELPER FUNCTIONS ####################
func (h *testHandler) getID(IdMap map[string]string, accountID string) (uuid.UUID, error) {
	ID, ok := IdMap[accountID]
	if !ok {
		return uuid.Nil, fmt.Errorf("account ID not found in map: %s", ID)
	}
	parsedID, err := uuid.Parse(ID)
	if err != nil {
		return uuid.Nil, fmt.Errorf("failed to parse account ID: %v", err)
	}

	return parsedID, nil
}

func (h *testHandler) saveID(idMap map[string]string, testId string, actualId string) {
	idMap[testId] = actualId
}
