db_host: "account_db"
db_port: 5432
db_user: "example_user"
db_password: "example_password"
db_name: "account_db"
grpc_host: "account_service"
grpc_port: 8082
migration_path: "/app/migrations"

root_account_id: "11111111-1111-1111-1111-111111111111"

monitoring: false