minio:
  host: "example-minio:9000"
  access:
    key: "example-access-key"
  secret:
    key: "example-secret-key"
  secure: false

database:
  username: "example_user"       # Corresponds to DatabaseUsername
  database: "example_db"         # Corresponds to DatabaseDatabase
  host: "example_db_host"        # Corresponds to DatabaseHost
  port: 5432                     # Corresponds to DatabasePort
  sslmode: "disable"             # Corresponds to DatabaseSSLMode
  timezone: "UTC"                # Corresponds to DatabaseTimezone
  password: "example_password"   # Corresponds to DatabasePassword

root:
  authority: "example_authority"

macaroon:
  root:
    key: "example_secret_key"

store:
  url: "http://example.com"
