services:
  store_service:
    build: 
      context: ./services/store
      dockerfile: Dockerfile.store
    ports:
      - "8080:8080"
    depends_on:
      - store_db
      - minio
    volumes:
      - ./services/store/internal/config/config.yaml:/app/config.yaml  # config file
      - ./init-config-example.json:/app/init-config-example.json  # init example
      - ./keys:/app/keys  # keys needed by store
    environment:
      - CONFIG_FILE_PATH=/app/config.yaml
    restart: always
    networks: 
      - kebeng-backend

  store_db:
    image: postgres:13
    restart: always
    volumes:
      - store_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=store_db
      - POSTGRES_USER=kebe_user
      - POSTGRES_PASSWORD=kebe
    ports:
      - "5432:5432"
    networks: 
      - kebeng-backend

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    restart: always
    networks: 
      - kebeng-backend

  account_service:
    build: 
      context: ./services/account
      dockerfile: Dockerfile.account
    ports:
      - "8081:8081"
    depends_on:
      - account_db
    volumes:
      - ./services/account/internal/config/config.yaml:/app/config.yaml  # config file
    environment:
      - CONFIG_FILE_PATH=/app/config.yaml
    restart: always
    networks: 
      - kebeng-backend

  account_db:
    image: postgres:13
    restart: always
    volumes:
      - account_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=account_db
      - POSTGRES_USER=kebe_user
      - POSTGRES_PASSWORD=kebe
    ports:
      - "5433:5432"
    networks: 
      - kebeng-backend

volumes:
  store_data:
  minio_data:
  account_data:

networks:
  kebeng-backend:
    driver: bridge
