services:
  store:
    build: 
      context: .
      dockerfile: build-aux/docker/Dockerfile.store
    ports:
      - "8080:8080"
    depends_on:
      - db
      - minio
    volumes:
      - ./config.yaml:/app/config.yaml  # config file
      - ./init-config-example.json:/app/init-config-example.json  # init example
      - ./keys:/app/keys  # keys needed by store
    environment:
      - CONFIG_FILE=/app/config.yaml
      - CONFIG_FILE_PATH=/app
    command: >
      sh -c "
        /app/kebeng-admin store initialize -i /app/init-config-example.json &&
        /app/kebeng-store store initialize -i /app/init-config-example.json
      "
    restart: always
    networks: 
      - kebeng-backend

  db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    # - ./migrations:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=kebe_store
      - POSTGRES_USER=kebe_user
      - POSTGRES_PASSWORD=kebe
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks: 
      - kebeng-backend

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    restart: always
    networks: 
      - kebeng-backend

volumes:
  db_data:
  minio_data:

networks:
  kebeng-backend:
    driver: bridge
