// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package assertion

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AssertionServiceClient is the client API for AssertionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssertionServiceClient interface {
	ProcessSnapBuildAssertion(ctx context.Context, in *SnapBuildAssertionRequest, opts ...grpc.CallOption) (*SnapBuildAssertionResponse, error)
	AddSnapRevisionAssertion(ctx context.Context, in *AddSnapRevisionAssertionRequest, opts ...grpc.CallOption) (*SnapRevisionAssertionResponse, error)
	AddAccountKeyAssertion(ctx context.Context, in *AddAccountKeyAssertionRequest, opts ...grpc.CallOption) (*AccountKeyAssertionResponse, error)
	AddSnapDeclarationAssertion(ctx context.Context, in *AddSnapDeclarationAssertionRequest, opts ...grpc.CallOption) (*SnapDeclarationAssertionResponse, error)
	AddAccountAssertion(ctx context.Context, in *AddAccountAssertionRequest, opts ...grpc.CallOption) (*AccountAssertionResponse, error)
	GetSnapRevisionAssertionBySHA3_384(ctx context.Context, in *GetSnapRevisionAssertionBySHA3_384Request, opts ...grpc.CallOption) (*SnapRevisionAssertionResponse, error)
	GetAccountKeyAssertionByPublicKeySha(ctx context.Context, in *GetAccountKeyAssertionByPublicKeyShaRequest, opts ...grpc.CallOption) (*AccountKeyAssertionResponse, error)
	GetSnapDeclarationAssertionBySnapID(ctx context.Context, in *GetSnapDeclarationAssertionBySnapIDRequest, opts ...grpc.CallOption) (*SnapDeclarationAssertionResponse, error)
	GetAccountAssertionByAccountID(ctx context.Context, in *GetAccountAssertionByAccountIDRequest, opts ...grpc.CallOption) (*AccountAssertionResponse, error)
}

type assertionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssertionServiceClient(cc grpc.ClientConnInterface) AssertionServiceClient {
	return &assertionServiceClient{cc}
}

func (c *assertionServiceClient) ProcessSnapBuildAssertion(ctx context.Context, in *SnapBuildAssertionRequest, opts ...grpc.CallOption) (*SnapBuildAssertionResponse, error) {
	out := new(SnapBuildAssertionResponse)
	err := c.cc.Invoke(ctx, "/assertion.AssertionService/ProcessSnapBuildAssertion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assertionServiceClient) AddSnapRevisionAssertion(ctx context.Context, in *AddSnapRevisionAssertionRequest, opts ...grpc.CallOption) (*SnapRevisionAssertionResponse, error) {
	out := new(SnapRevisionAssertionResponse)
	err := c.cc.Invoke(ctx, "/assertion.AssertionService/AddSnapRevisionAssertion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assertionServiceClient) AddAccountKeyAssertion(ctx context.Context, in *AddAccountKeyAssertionRequest, opts ...grpc.CallOption) (*AccountKeyAssertionResponse, error) {
	out := new(AccountKeyAssertionResponse)
	err := c.cc.Invoke(ctx, "/assertion.AssertionService/AddAccountKeyAssertion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assertionServiceClient) AddSnapDeclarationAssertion(ctx context.Context, in *AddSnapDeclarationAssertionRequest, opts ...grpc.CallOption) (*SnapDeclarationAssertionResponse, error) {
	out := new(SnapDeclarationAssertionResponse)
	err := c.cc.Invoke(ctx, "/assertion.AssertionService/AddSnapDeclarationAssertion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assertionServiceClient) AddAccountAssertion(ctx context.Context, in *AddAccountAssertionRequest, opts ...grpc.CallOption) (*AccountAssertionResponse, error) {
	out := new(AccountAssertionResponse)
	err := c.cc.Invoke(ctx, "/assertion.AssertionService/AddAccountAssertion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assertionServiceClient) GetSnapRevisionAssertionBySHA3_384(ctx context.Context, in *GetSnapRevisionAssertionBySHA3_384Request, opts ...grpc.CallOption) (*SnapRevisionAssertionResponse, error) {
	out := new(SnapRevisionAssertionResponse)
	err := c.cc.Invoke(ctx, "/assertion.AssertionService/GetSnapRevisionAssertionBySHA3_384", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assertionServiceClient) GetAccountKeyAssertionByPublicKeySha(ctx context.Context, in *GetAccountKeyAssertionByPublicKeyShaRequest, opts ...grpc.CallOption) (*AccountKeyAssertionResponse, error) {
	out := new(AccountKeyAssertionResponse)
	err := c.cc.Invoke(ctx, "/assertion.AssertionService/GetAccountKeyAssertionByPublicKeySha", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assertionServiceClient) GetSnapDeclarationAssertionBySnapID(ctx context.Context, in *GetSnapDeclarationAssertionBySnapIDRequest, opts ...grpc.CallOption) (*SnapDeclarationAssertionResponse, error) {
	out := new(SnapDeclarationAssertionResponse)
	err := c.cc.Invoke(ctx, "/assertion.AssertionService/GetSnapDeclarationAssertionBySnapID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assertionServiceClient) GetAccountAssertionByAccountID(ctx context.Context, in *GetAccountAssertionByAccountIDRequest, opts ...grpc.CallOption) (*AccountAssertionResponse, error) {
	out := new(AccountAssertionResponse)
	err := c.cc.Invoke(ctx, "/assertion.AssertionService/GetAccountAssertionByAccountID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssertionServiceServer is the server API for AssertionService service.
// All implementations must embed UnimplementedAssertionServiceServer
// for forward compatibility
type AssertionServiceServer interface {
	ProcessSnapBuildAssertion(context.Context, *SnapBuildAssertionRequest) (*SnapBuildAssertionResponse, error)
	AddSnapRevisionAssertion(context.Context, *AddSnapRevisionAssertionRequest) (*SnapRevisionAssertionResponse, error)
	AddAccountKeyAssertion(context.Context, *AddAccountKeyAssertionRequest) (*AccountKeyAssertionResponse, error)
	AddSnapDeclarationAssertion(context.Context, *AddSnapDeclarationAssertionRequest) (*SnapDeclarationAssertionResponse, error)
	AddAccountAssertion(context.Context, *AddAccountAssertionRequest) (*AccountAssertionResponse, error)
	GetSnapRevisionAssertionBySHA3_384(context.Context, *GetSnapRevisionAssertionBySHA3_384Request) (*SnapRevisionAssertionResponse, error)
	GetAccountKeyAssertionByPublicKeySha(context.Context, *GetAccountKeyAssertionByPublicKeyShaRequest) (*AccountKeyAssertionResponse, error)
	GetSnapDeclarationAssertionBySnapID(context.Context, *GetSnapDeclarationAssertionBySnapIDRequest) (*SnapDeclarationAssertionResponse, error)
	GetAccountAssertionByAccountID(context.Context, *GetAccountAssertionByAccountIDRequest) (*AccountAssertionResponse, error)
	mustEmbedUnimplementedAssertionServiceServer()
}

// UnimplementedAssertionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAssertionServiceServer struct {
}

func (UnimplementedAssertionServiceServer) ProcessSnapBuildAssertion(context.Context, *SnapBuildAssertionRequest) (*SnapBuildAssertionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessSnapBuildAssertion not implemented")
}
func (UnimplementedAssertionServiceServer) AddSnapRevisionAssertion(context.Context, *AddSnapRevisionAssertionRequest) (*SnapRevisionAssertionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSnapRevisionAssertion not implemented")
}
func (UnimplementedAssertionServiceServer) AddAccountKeyAssertion(context.Context, *AddAccountKeyAssertionRequest) (*AccountKeyAssertionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAccountKeyAssertion not implemented")
}
func (UnimplementedAssertionServiceServer) AddSnapDeclarationAssertion(context.Context, *AddSnapDeclarationAssertionRequest) (*SnapDeclarationAssertionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSnapDeclarationAssertion not implemented")
}
func (UnimplementedAssertionServiceServer) AddAccountAssertion(context.Context, *AddAccountAssertionRequest) (*AccountAssertionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAccountAssertion not implemented")
}
func (UnimplementedAssertionServiceServer) GetSnapRevisionAssertionBySHA3_384(context.Context, *GetSnapRevisionAssertionBySHA3_384Request) (*SnapRevisionAssertionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnapRevisionAssertionBySHA3_384 not implemented")
}
func (UnimplementedAssertionServiceServer) GetAccountKeyAssertionByPublicKeySha(context.Context, *GetAccountKeyAssertionByPublicKeyShaRequest) (*AccountKeyAssertionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountKeyAssertionByPublicKeySha not implemented")
}
func (UnimplementedAssertionServiceServer) GetSnapDeclarationAssertionBySnapID(context.Context, *GetSnapDeclarationAssertionBySnapIDRequest) (*SnapDeclarationAssertionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnapDeclarationAssertionBySnapID not implemented")
}
func (UnimplementedAssertionServiceServer) GetAccountAssertionByAccountID(context.Context, *GetAccountAssertionByAccountIDRequest) (*AccountAssertionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountAssertionByAccountID not implemented")
}
func (UnimplementedAssertionServiceServer) mustEmbedUnimplementedAssertionServiceServer() {}

// UnsafeAssertionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssertionServiceServer will
// result in compilation errors.
type UnsafeAssertionServiceServer interface {
	mustEmbedUnimplementedAssertionServiceServer()
}

func RegisterAssertionServiceServer(s grpc.ServiceRegistrar, srv AssertionServiceServer) {
	s.RegisterService(&AssertionService_ServiceDesc, srv)
}

func _AssertionService_ProcessSnapBuildAssertion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapBuildAssertionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssertionServiceServer).ProcessSnapBuildAssertion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/assertion.AssertionService/ProcessSnapBuildAssertion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssertionServiceServer).ProcessSnapBuildAssertion(ctx, req.(*SnapBuildAssertionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssertionService_AddSnapRevisionAssertion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSnapRevisionAssertionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssertionServiceServer).AddSnapRevisionAssertion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/assertion.AssertionService/AddSnapRevisionAssertion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssertionServiceServer).AddSnapRevisionAssertion(ctx, req.(*AddSnapRevisionAssertionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssertionService_AddAccountKeyAssertion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAccountKeyAssertionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssertionServiceServer).AddAccountKeyAssertion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/assertion.AssertionService/AddAccountKeyAssertion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssertionServiceServer).AddAccountKeyAssertion(ctx, req.(*AddAccountKeyAssertionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssertionService_AddSnapDeclarationAssertion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSnapDeclarationAssertionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssertionServiceServer).AddSnapDeclarationAssertion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/assertion.AssertionService/AddSnapDeclarationAssertion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssertionServiceServer).AddSnapDeclarationAssertion(ctx, req.(*AddSnapDeclarationAssertionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssertionService_AddAccountAssertion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAccountAssertionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssertionServiceServer).AddAccountAssertion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/assertion.AssertionService/AddAccountAssertion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssertionServiceServer).AddAccountAssertion(ctx, req.(*AddAccountAssertionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssertionService_GetSnapRevisionAssertionBySHA3_384_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapRevisionAssertionBySHA3_384Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssertionServiceServer).GetSnapRevisionAssertionBySHA3_384(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/assertion.AssertionService/GetSnapRevisionAssertionBySHA3_384",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssertionServiceServer).GetSnapRevisionAssertionBySHA3_384(ctx, req.(*GetSnapRevisionAssertionBySHA3_384Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssertionService_GetAccountKeyAssertionByPublicKeySha_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountKeyAssertionByPublicKeyShaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssertionServiceServer).GetAccountKeyAssertionByPublicKeySha(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/assertion.AssertionService/GetAccountKeyAssertionByPublicKeySha",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssertionServiceServer).GetAccountKeyAssertionByPublicKeySha(ctx, req.(*GetAccountKeyAssertionByPublicKeyShaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssertionService_GetSnapDeclarationAssertionBySnapID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapDeclarationAssertionBySnapIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssertionServiceServer).GetSnapDeclarationAssertionBySnapID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/assertion.AssertionService/GetSnapDeclarationAssertionBySnapID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssertionServiceServer).GetSnapDeclarationAssertionBySnapID(ctx, req.(*GetSnapDeclarationAssertionBySnapIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssertionService_GetAccountAssertionByAccountID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountAssertionByAccountIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssertionServiceServer).GetAccountAssertionByAccountID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/assertion.AssertionService/GetAccountAssertionByAccountID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssertionServiceServer).GetAccountAssertionByAccountID(ctx, req.(*GetAccountAssertionByAccountIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssertionService_ServiceDesc is the grpc.ServiceDesc for AssertionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssertionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assertion.AssertionService",
	HandlerType: (*AssertionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessSnapBuildAssertion",
			Handler:    _AssertionService_ProcessSnapBuildAssertion_Handler,
		},
		{
			MethodName: "AddSnapRevisionAssertion",
			Handler:    _AssertionService_AddSnapRevisionAssertion_Handler,
		},
		{
			MethodName: "AddAccountKeyAssertion",
			Handler:    _AssertionService_AddAccountKeyAssertion_Handler,
		},
		{
			MethodName: "AddSnapDeclarationAssertion",
			Handler:    _AssertionService_AddSnapDeclarationAssertion_Handler,
		},
		{
			MethodName: "AddAccountAssertion",
			Handler:    _AssertionService_AddAccountAssertion_Handler,
		},
		{
			MethodName: "GetSnapRevisionAssertionBySHA3_384",
			Handler:    _AssertionService_GetSnapRevisionAssertionBySHA3_384_Handler,
		},
		{
			MethodName: "GetAccountKeyAssertionByPublicKeySha",
			Handler:    _AssertionService_GetAccountKeyAssertionByPublicKeySha_Handler,
		},
		{
			MethodName: "GetSnapDeclarationAssertionBySnapID",
			Handler:    _AssertionService_GetSnapDeclarationAssertionBySnapID_Handler,
		},
		{
			MethodName: "GetAccountAssertionByAccountID",
			Handler:    _AssertionService_GetAccountAssertionByAccountID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assertion.proto",
}
