// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: assertion.proto

package assertion

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssertionService_ProcessSnapBuildAssertion_FullMethodName = "/assertion.AssertionService/ProcessSnapBuildAssertion"
	AssertionService_AddSnapRevisionAssertion_FullMethodName  = "/assertion.AssertionService/AddSnapRevisionAssertion"
)

// AssertionServiceClient is the client API for AssertionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssertionServiceClient interface {
	ProcessSnapBuildAssertion(ctx context.Context, in *SnapBuildAssertionRequest, opts ...grpc.CallOption) (*SnapBuildAssertionResponse, error)
	AddSnapRevisionAssertion(ctx context.Context, in *AddSnapRevisionAssertionRequest, opts ...grpc.CallOption) (*SnapRevisionAssertionResponse, error)
}

type assertionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssertionServiceClient(cc grpc.ClientConnInterface) AssertionServiceClient {
	return &assertionServiceClient{cc}
}

func (c *assertionServiceClient) ProcessSnapBuildAssertion(ctx context.Context, in *SnapBuildAssertionRequest, opts ...grpc.CallOption) (*SnapBuildAssertionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapBuildAssertionResponse)
	err := c.cc.Invoke(ctx, AssertionService_ProcessSnapBuildAssertion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assertionServiceClient) AddSnapRevisionAssertion(ctx context.Context, in *AddSnapRevisionAssertionRequest, opts ...grpc.CallOption) (*SnapRevisionAssertionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapRevisionAssertionResponse)
	err := c.cc.Invoke(ctx, AssertionService_AddSnapRevisionAssertion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssertionServiceServer is the server API for AssertionService service.
// All implementations must embed UnimplementedAssertionServiceServer
// for forward compatibility.
type AssertionServiceServer interface {
	ProcessSnapBuildAssertion(context.Context, *SnapBuildAssertionRequest) (*SnapBuildAssertionResponse, error)
	AddSnapRevisionAssertion(context.Context, *AddSnapRevisionAssertionRequest) (*SnapRevisionAssertionResponse, error)
	mustEmbedUnimplementedAssertionServiceServer()
}

// UnimplementedAssertionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssertionServiceServer struct{}

func (UnimplementedAssertionServiceServer) ProcessSnapBuildAssertion(context.Context, *SnapBuildAssertionRequest) (*SnapBuildAssertionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessSnapBuildAssertion not implemented")
}
func (UnimplementedAssertionServiceServer) AddSnapRevisionAssertion(context.Context, *AddSnapRevisionAssertionRequest) (*SnapRevisionAssertionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSnapRevisionAssertion not implemented")
}
func (UnimplementedAssertionServiceServer) mustEmbedUnimplementedAssertionServiceServer() {}
func (UnimplementedAssertionServiceServer) testEmbeddedByValue()                          {}

// UnsafeAssertionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssertionServiceServer will
// result in compilation errors.
type UnsafeAssertionServiceServer interface {
	mustEmbedUnimplementedAssertionServiceServer()
}

func RegisterAssertionServiceServer(s grpc.ServiceRegistrar, srv AssertionServiceServer) {
	// If the following call pancis, it indicates UnimplementedAssertionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssertionService_ServiceDesc, srv)
}

func _AssertionService_ProcessSnapBuildAssertion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapBuildAssertionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssertionServiceServer).ProcessSnapBuildAssertion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssertionService_ProcessSnapBuildAssertion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssertionServiceServer).ProcessSnapBuildAssertion(ctx, req.(*SnapBuildAssertionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssertionService_AddSnapRevisionAssertion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSnapRevisionAssertionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssertionServiceServer).AddSnapRevisionAssertion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssertionService_AddSnapRevisionAssertion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssertionServiceServer).AddSnapRevisionAssertion(ctx, req.(*AddSnapRevisionAssertionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssertionService_ServiceDesc is the grpc.ServiceDesc for AssertionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssertionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assertion.AssertionService",
	HandlerType: (*AssertionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessSnapBuildAssertion",
			Handler:    _AssertionService_ProcessSnapBuildAssertion_Handler,
		},
		{
			MethodName: "AddSnapRevisionAssertion",
			Handler:    _AssertionService_AddSnapRevisionAssertion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assertion.proto",
}
