syntax = "proto3";

import "common/cerror/proto/error.proto";

package assertion;
option go_package = "github.com/idlab-discover/kebeng/services/assertion/proto;assertion";

service AssertionService {
    rpc ProcessSnapBuildAssertion(SnapBuildAssertionRequest) returns (SnapBuildAssertionResponse);
}

message SnapBuildAssertionRequest {
    bytes assertion = 1;
}

message SnapBuildAssertionResponse {
    string authority_id = 1;
    string grade = 2;
    string sign_key_sha3_384 = 3;
    string snap_id = 4;
    string snap_sha3_384 = 5;
    string snap_size = 6;
    string timestamp = 7;
    string revision = 8;
    string type = 9;
    string developer_id = 10;
    repeated proto.Error errors = 11;
}
