// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: assertion.proto

package assertion

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssertionService_ProcessSnapBuildAssertion_FullMethodName           = "/assertion.AssertionService/ProcessSnapBuildAssertion"
	AssertionService_AddSnapRevisionAssertion_FullMethodName            = "/assertion.AssertionService/AddSnapRevisionAssertion"
	AssertionService_AddAccountKeyAssertion_FullMethodName              = "/assertion.AssertionService/AddAccountKeyAssertion"
	AssertionService_AddSnapDeclarationAssertion_FullMethodName         = "/assertion.AssertionService/AddSnapDeclarationAssertion"
	AssertionService_GetSnapRevisionAssertionBySHA3_384_FullMethodName  = "/assertion.AssertionService/GetSnapRevisionAssertionBySHA3_384"
	AssertionService_GetAccountKeyAssertionByName_FullMethodName        = "/assertion.AssertionService/GetAccountKeyAssertionByName"
	AssertionService_GetSnapDeclarationAssertionBySnapID_FullMethodName = "/assertion.AssertionService/GetSnapDeclarationAssertionBySnapID"
)

// AssertionServiceClient is the client API for AssertionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssertionServiceClient interface {
	ProcessSnapBuildAssertion(ctx context.Context, in *SnapBuildAssertionRequest, opts ...grpc.CallOption) (*SnapBuildAssertionResponse, error)
	AddSnapRevisionAssertion(ctx context.Context, in *AddSnapRevisionAssertionRequest, opts ...grpc.CallOption) (*SnapRevisionAssertionResponse, error)
	AddAccountKeyAssertion(ctx context.Context, in *AddAccountKeyAssertionRequest, opts ...grpc.CallOption) (*AccountKeyAssertionResponse, error)
	AddSnapDeclarationAssertion(ctx context.Context, in *AddSnapDeclarationAssertionRequest, opts ...grpc.CallOption) (*SnapDeclarationAssertionResponse, error)
	GetSnapRevisionAssertionBySHA3_384(ctx context.Context, in *GetSnapRevisionAssertionBySHA3_384Request, opts ...grpc.CallOption) (*SnapRevisionAssertionResponse, error)
	GetAccountKeyAssertionByName(ctx context.Context, in *GetAccountKeyAssertionByNameRequest, opts ...grpc.CallOption) (*AccountKeyAssertionResponse, error)
	GetSnapDeclarationAssertionBySnapID(ctx context.Context, in *GetSnapDeclarationAssertionBySnapIDRequest, opts ...grpc.CallOption) (*SnapDeclarationAssertionResponse, error)
}

type assertionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssertionServiceClient(cc grpc.ClientConnInterface) AssertionServiceClient {
	return &assertionServiceClient{cc}
}

func (c *assertionServiceClient) ProcessSnapBuildAssertion(ctx context.Context, in *SnapBuildAssertionRequest, opts ...grpc.CallOption) (*SnapBuildAssertionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapBuildAssertionResponse)
	err := c.cc.Invoke(ctx, AssertionService_ProcessSnapBuildAssertion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assertionServiceClient) AddSnapRevisionAssertion(ctx context.Context, in *AddSnapRevisionAssertionRequest, opts ...grpc.CallOption) (*SnapRevisionAssertionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapRevisionAssertionResponse)
	err := c.cc.Invoke(ctx, AssertionService_AddSnapRevisionAssertion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assertionServiceClient) AddAccountKeyAssertion(ctx context.Context, in *AddAccountKeyAssertionRequest, opts ...grpc.CallOption) (*AccountKeyAssertionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountKeyAssertionResponse)
	err := c.cc.Invoke(ctx, AssertionService_AddAccountKeyAssertion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assertionServiceClient) AddSnapDeclarationAssertion(ctx context.Context, in *AddSnapDeclarationAssertionRequest, opts ...grpc.CallOption) (*SnapDeclarationAssertionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapDeclarationAssertionResponse)
	err := c.cc.Invoke(ctx, AssertionService_AddSnapDeclarationAssertion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assertionServiceClient) GetSnapRevisionAssertionBySHA3_384(ctx context.Context, in *GetSnapRevisionAssertionBySHA3_384Request, opts ...grpc.CallOption) (*SnapRevisionAssertionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapRevisionAssertionResponse)
	err := c.cc.Invoke(ctx, AssertionService_GetSnapRevisionAssertionBySHA3_384_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assertionServiceClient) GetAccountKeyAssertionByName(ctx context.Context, in *GetAccountKeyAssertionByNameRequest, opts ...grpc.CallOption) (*AccountKeyAssertionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountKeyAssertionResponse)
	err := c.cc.Invoke(ctx, AssertionService_GetAccountKeyAssertionByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assertionServiceClient) GetSnapDeclarationAssertionBySnapID(ctx context.Context, in *GetSnapDeclarationAssertionBySnapIDRequest, opts ...grpc.CallOption) (*SnapDeclarationAssertionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapDeclarationAssertionResponse)
	err := c.cc.Invoke(ctx, AssertionService_GetSnapDeclarationAssertionBySnapID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssertionServiceServer is the server API for AssertionService service.
// All implementations must embed UnimplementedAssertionServiceServer
// for forward compatibility.
type AssertionServiceServer interface {
	ProcessSnapBuildAssertion(context.Context, *SnapBuildAssertionRequest) (*SnapBuildAssertionResponse, error)
	AddSnapRevisionAssertion(context.Context, *AddSnapRevisionAssertionRequest) (*SnapRevisionAssertionResponse, error)
	AddAccountKeyAssertion(context.Context, *AddAccountKeyAssertionRequest) (*AccountKeyAssertionResponse, error)
	AddSnapDeclarationAssertion(context.Context, *AddSnapDeclarationAssertionRequest) (*SnapDeclarationAssertionResponse, error)
	GetSnapRevisionAssertionBySHA3_384(context.Context, *GetSnapRevisionAssertionBySHA3_384Request) (*SnapRevisionAssertionResponse, error)
	GetAccountKeyAssertionByName(context.Context, *GetAccountKeyAssertionByNameRequest) (*AccountKeyAssertionResponse, error)
	GetSnapDeclarationAssertionBySnapID(context.Context, *GetSnapDeclarationAssertionBySnapIDRequest) (*SnapDeclarationAssertionResponse, error)
	mustEmbedUnimplementedAssertionServiceServer()
}

// UnimplementedAssertionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssertionServiceServer struct{}

func (UnimplementedAssertionServiceServer) ProcessSnapBuildAssertion(context.Context, *SnapBuildAssertionRequest) (*SnapBuildAssertionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessSnapBuildAssertion not implemented")
}
func (UnimplementedAssertionServiceServer) AddSnapRevisionAssertion(context.Context, *AddSnapRevisionAssertionRequest) (*SnapRevisionAssertionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSnapRevisionAssertion not implemented")
}
func (UnimplementedAssertionServiceServer) AddAccountKeyAssertion(context.Context, *AddAccountKeyAssertionRequest) (*AccountKeyAssertionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAccountKeyAssertion not implemented")
}
func (UnimplementedAssertionServiceServer) AddSnapDeclarationAssertion(context.Context, *AddSnapDeclarationAssertionRequest) (*SnapDeclarationAssertionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSnapDeclarationAssertion not implemented")
}
func (UnimplementedAssertionServiceServer) GetSnapRevisionAssertionBySHA3_384(context.Context, *GetSnapRevisionAssertionBySHA3_384Request) (*SnapRevisionAssertionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnapRevisionAssertionBySHA3_384 not implemented")
}
func (UnimplementedAssertionServiceServer) GetAccountKeyAssertionByName(context.Context, *GetAccountKeyAssertionByNameRequest) (*AccountKeyAssertionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountKeyAssertionByName not implemented")
}
func (UnimplementedAssertionServiceServer) GetSnapDeclarationAssertionBySnapID(context.Context, *GetSnapDeclarationAssertionBySnapIDRequest) (*SnapDeclarationAssertionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnapDeclarationAssertionBySnapID not implemented")
}
func (UnimplementedAssertionServiceServer) mustEmbedUnimplementedAssertionServiceServer() {}
func (UnimplementedAssertionServiceServer) testEmbeddedByValue()                          {}

// UnsafeAssertionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssertionServiceServer will
// result in compilation errors.
type UnsafeAssertionServiceServer interface {
	mustEmbedUnimplementedAssertionServiceServer()
}

func RegisterAssertionServiceServer(s grpc.ServiceRegistrar, srv AssertionServiceServer) {
	// If the following call pancis, it indicates UnimplementedAssertionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssertionService_ServiceDesc, srv)
}

func _AssertionService_ProcessSnapBuildAssertion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapBuildAssertionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssertionServiceServer).ProcessSnapBuildAssertion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssertionService_ProcessSnapBuildAssertion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssertionServiceServer).ProcessSnapBuildAssertion(ctx, req.(*SnapBuildAssertionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssertionService_AddSnapRevisionAssertion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSnapRevisionAssertionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssertionServiceServer).AddSnapRevisionAssertion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssertionService_AddSnapRevisionAssertion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssertionServiceServer).AddSnapRevisionAssertion(ctx, req.(*AddSnapRevisionAssertionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssertionService_AddAccountKeyAssertion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAccountKeyAssertionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssertionServiceServer).AddAccountKeyAssertion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssertionService_AddAccountKeyAssertion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssertionServiceServer).AddAccountKeyAssertion(ctx, req.(*AddAccountKeyAssertionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssertionService_AddSnapDeclarationAssertion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSnapDeclarationAssertionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssertionServiceServer).AddSnapDeclarationAssertion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssertionService_AddSnapDeclarationAssertion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssertionServiceServer).AddSnapDeclarationAssertion(ctx, req.(*AddSnapDeclarationAssertionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssertionService_GetSnapRevisionAssertionBySHA3_384_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapRevisionAssertionBySHA3_384Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssertionServiceServer).GetSnapRevisionAssertionBySHA3_384(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssertionService_GetSnapRevisionAssertionBySHA3_384_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssertionServiceServer).GetSnapRevisionAssertionBySHA3_384(ctx, req.(*GetSnapRevisionAssertionBySHA3_384Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssertionService_GetAccountKeyAssertionByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountKeyAssertionByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssertionServiceServer).GetAccountKeyAssertionByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssertionService_GetAccountKeyAssertionByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssertionServiceServer).GetAccountKeyAssertionByName(ctx, req.(*GetAccountKeyAssertionByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssertionService_GetSnapDeclarationAssertionBySnapID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapDeclarationAssertionBySnapIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssertionServiceServer).GetSnapDeclarationAssertionBySnapID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssertionService_GetSnapDeclarationAssertionBySnapID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssertionServiceServer).GetSnapDeclarationAssertionBySnapID(ctx, req.(*GetSnapDeclarationAssertionBySnapIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssertionService_ServiceDesc is the grpc.ServiceDesc for AssertionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssertionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assertion.AssertionService",
	HandlerType: (*AssertionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessSnapBuildAssertion",
			Handler:    _AssertionService_ProcessSnapBuildAssertion_Handler,
		},
		{
			MethodName: "AddSnapRevisionAssertion",
			Handler:    _AssertionService_AddSnapRevisionAssertion_Handler,
		},
		{
			MethodName: "AddAccountKeyAssertion",
			Handler:    _AssertionService_AddAccountKeyAssertion_Handler,
		},
		{
			MethodName: "AddSnapDeclarationAssertion",
			Handler:    _AssertionService_AddSnapDeclarationAssertion_Handler,
		},
		{
			MethodName: "GetSnapRevisionAssertionBySHA3_384",
			Handler:    _AssertionService_GetSnapRevisionAssertionBySHA3_384_Handler,
		},
		{
			MethodName: "GetAccountKeyAssertionByName",
			Handler:    _AssertionService_GetAccountKeyAssertionByName_Handler,
		},
		{
			MethodName: "GetSnapDeclarationAssertionBySnapID",
			Handler:    _AssertionService_GetSnapDeclarationAssertionBySnapID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assertion.proto",
}
