FROM golang:1.16 AS builder

WORKDIR /app
COPY . . 

RUN go build -o /bin/kebeng-admin bin/admin/main.go
RUN go build -o /bin/kebeng-store bin/store/main.go

FROM golang:1.16
WORKDIR /app

COPY --from=builder /bin/kebeng-store /app/kebeng-store
COPY --from=builder /bin/kebeng-admin /app/kebeng-admin

EXPOSE 8080
