mongodb_uri: "mongodb://root:rootpassword@mongo_db:27017/assertions?authSource=admin"

grpc_host: "assertion_service"
grpc_port: 8083

root_key_path: "/app/keys/root_key.pem"
root_account_id: "123e4567-e89b-12d3-a456-426614174000"

authority_id: "example_authority"
store_name: "ExampleStore"

monitoring: true