mongodb_db: "assertions"
mongodb_user: "root"
mongodb_password: "rootpassword"
mongodb_host: "mongo_db"
mongodb_port: 27017
mongodb_auth_source: "admin"

grpc_host: "assertion_service"
grpc_port: 8083

root_key_path: "/app/keys/root_key.pem"
root_account_id: "123e4567-e89b-12d3-a456-426614174000"

authority_id: "example_authority"
store_name: "ExampleStore"

monitoring: true