// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package store

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoreServiceClient interface {
	RegisterSnapName(ctx context.Context, in *RegisterSnapNameRequest, opts ...grpc.CallOption) (*RegisterSnapNameResponse, error)
	GetRevisions(ctx context.Context, in *GetRevisionsRequest, opts ...grpc.CallOption) (*GetRevisionsResponse, error)
	GetEntries(ctx context.Context, in *GetEntriesRequest, opts ...grpc.CallOption) (*GetEntriesResponse, error)
	GetEntriesByAccountId(ctx context.Context, in *GetEntriesByAccountIdRequest, opts ...grpc.CallOption) (*GetEntriesResponse, error)
	GetRevisionsByEntryIds(ctx context.Context, in *GetRevisionsByEntryIdRequests, opts ...grpc.CallOption) (*GetRevisionsByEntryIdResponses, error)
	GetLatestRevision(ctx context.Context, in *GetLatestRevisionRequest, opts ...grpc.CallOption) (*GetRevisionResponse, error)
	SnapDownload(ctx context.Context, in *SnapDownloadRequest, opts ...grpc.CallOption) (StoreService_SnapDownloadClient, error)
	UnscannedUpload(ctx context.Context, opts ...grpc.CallOption) (StoreService_UnscannedUploadClient, error)
	AddUpload(ctx context.Context, in *AddUploadRequest, opts ...grpc.CallOption) (*AddUploadResponse, error)
}

type storeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreServiceClient(cc grpc.ClientConnInterface) StoreServiceClient {
	return &storeServiceClient{cc}
}

func (c *storeServiceClient) RegisterSnapName(ctx context.Context, in *RegisterSnapNameRequest, opts ...grpc.CallOption) (*RegisterSnapNameResponse, error) {
	out := new(RegisterSnapNameResponse)
	err := c.cc.Invoke(ctx, "/store.StoreService/RegisterSnapName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetRevisions(ctx context.Context, in *GetRevisionsRequest, opts ...grpc.CallOption) (*GetRevisionsResponse, error) {
	out := new(GetRevisionsResponse)
	err := c.cc.Invoke(ctx, "/store.StoreService/GetRevisions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetEntries(ctx context.Context, in *GetEntriesRequest, opts ...grpc.CallOption) (*GetEntriesResponse, error) {
	out := new(GetEntriesResponse)
	err := c.cc.Invoke(ctx, "/store.StoreService/GetEntries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetEntriesByAccountId(ctx context.Context, in *GetEntriesByAccountIdRequest, opts ...grpc.CallOption) (*GetEntriesResponse, error) {
	out := new(GetEntriesResponse)
	err := c.cc.Invoke(ctx, "/store.StoreService/GetEntriesByAccountId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetRevisionsByEntryIds(ctx context.Context, in *GetRevisionsByEntryIdRequests, opts ...grpc.CallOption) (*GetRevisionsByEntryIdResponses, error) {
	out := new(GetRevisionsByEntryIdResponses)
	err := c.cc.Invoke(ctx, "/store.StoreService/GetRevisionsByEntryIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetLatestRevision(ctx context.Context, in *GetLatestRevisionRequest, opts ...grpc.CallOption) (*GetRevisionResponse, error) {
	out := new(GetRevisionResponse)
	err := c.cc.Invoke(ctx, "/store.StoreService/GetLatestRevision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) SnapDownload(ctx context.Context, in *SnapDownloadRequest, opts ...grpc.CallOption) (StoreService_SnapDownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &StoreService_ServiceDesc.Streams[0], "/store.StoreService/SnapDownload", opts...)
	if err != nil {
		return nil, err
	}
	x := &storeServiceSnapDownloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StoreService_SnapDownloadClient interface {
	Recv() (*SnapDownloadResponse, error)
	grpc.ClientStream
}

type storeServiceSnapDownloadClient struct {
	grpc.ClientStream
}

func (x *storeServiceSnapDownloadClient) Recv() (*SnapDownloadResponse, error) {
	m := new(SnapDownloadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storeServiceClient) UnscannedUpload(ctx context.Context, opts ...grpc.CallOption) (StoreService_UnscannedUploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &StoreService_ServiceDesc.Streams[1], "/store.StoreService/UnscannedUpload", opts...)
	if err != nil {
		return nil, err
	}
	x := &storeServiceUnscannedUploadClient{stream}
	return x, nil
}

type StoreService_UnscannedUploadClient interface {
	Send(*UnscannedUploadRequest) error
	CloseAndRecv() (*UnscannedUploadCompleteResponse, error)
	grpc.ClientStream
}

type storeServiceUnscannedUploadClient struct {
	grpc.ClientStream
}

func (x *storeServiceUnscannedUploadClient) Send(m *UnscannedUploadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storeServiceUnscannedUploadClient) CloseAndRecv() (*UnscannedUploadCompleteResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UnscannedUploadCompleteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storeServiceClient) AddUpload(ctx context.Context, in *AddUploadRequest, opts ...grpc.CallOption) (*AddUploadResponse, error) {
	out := new(AddUploadResponse)
	err := c.cc.Invoke(ctx, "/store.StoreService/AddUpload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServiceServer is the server API for StoreService service.
// All implementations must embed UnimplementedStoreServiceServer
// for forward compatibility
type StoreServiceServer interface {
	RegisterSnapName(context.Context, *RegisterSnapNameRequest) (*RegisterSnapNameResponse, error)
	GetRevisions(context.Context, *GetRevisionsRequest) (*GetRevisionsResponse, error)
	GetEntries(context.Context, *GetEntriesRequest) (*GetEntriesResponse, error)
	GetEntriesByAccountId(context.Context, *GetEntriesByAccountIdRequest) (*GetEntriesResponse, error)
	GetRevisionsByEntryIds(context.Context, *GetRevisionsByEntryIdRequests) (*GetRevisionsByEntryIdResponses, error)
	GetLatestRevision(context.Context, *GetLatestRevisionRequest) (*GetRevisionResponse, error)
	SnapDownload(*SnapDownloadRequest, StoreService_SnapDownloadServer) error
	UnscannedUpload(StoreService_UnscannedUploadServer) error
	AddUpload(context.Context, *AddUploadRequest) (*AddUploadResponse, error)
	mustEmbedUnimplementedStoreServiceServer()
}

// UnimplementedStoreServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStoreServiceServer struct {
}

func (UnimplementedStoreServiceServer) RegisterSnapName(context.Context, *RegisterSnapNameRequest) (*RegisterSnapNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSnapName not implemented")
}
func (UnimplementedStoreServiceServer) GetRevisions(context.Context, *GetRevisionsRequest) (*GetRevisionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRevisions not implemented")
}
func (UnimplementedStoreServiceServer) GetEntries(context.Context, *GetEntriesRequest) (*GetEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntries not implemented")
}
func (UnimplementedStoreServiceServer) GetEntriesByAccountId(context.Context, *GetEntriesByAccountIdRequest) (*GetEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntriesByAccountId not implemented")
}
func (UnimplementedStoreServiceServer) GetRevisionsByEntryIds(context.Context, *GetRevisionsByEntryIdRequests) (*GetRevisionsByEntryIdResponses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRevisionsByEntryIds not implemented")
}
func (UnimplementedStoreServiceServer) GetLatestRevision(context.Context, *GetLatestRevisionRequest) (*GetRevisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestRevision not implemented")
}
func (UnimplementedStoreServiceServer) SnapDownload(*SnapDownloadRequest, StoreService_SnapDownloadServer) error {
	return status.Errorf(codes.Unimplemented, "method SnapDownload not implemented")
}
func (UnimplementedStoreServiceServer) UnscannedUpload(StoreService_UnscannedUploadServer) error {
	return status.Errorf(codes.Unimplemented, "method UnscannedUpload not implemented")
}
func (UnimplementedStoreServiceServer) AddUpload(context.Context, *AddUploadRequest) (*AddUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUpload not implemented")
}
func (UnimplementedStoreServiceServer) mustEmbedUnimplementedStoreServiceServer() {}

// UnsafeStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreServiceServer will
// result in compilation errors.
type UnsafeStoreServiceServer interface {
	mustEmbedUnimplementedStoreServiceServer()
}

func RegisterStoreServiceServer(s grpc.ServiceRegistrar, srv StoreServiceServer) {
	s.RegisterService(&StoreService_ServiceDesc, srv)
}

func _StoreService_RegisterSnapName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSnapNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).RegisterSnapName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.StoreService/RegisterSnapName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).RegisterSnapName(ctx, req.(*RegisterSnapNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetRevisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRevisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetRevisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.StoreService/GetRevisions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetRevisions(ctx, req.(*GetRevisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.StoreService/GetEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetEntries(ctx, req.(*GetEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetEntriesByAccountId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntriesByAccountIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetEntriesByAccountId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.StoreService/GetEntriesByAccountId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetEntriesByAccountId(ctx, req.(*GetEntriesByAccountIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetRevisionsByEntryIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRevisionsByEntryIdRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetRevisionsByEntryIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.StoreService/GetRevisionsByEntryIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetRevisionsByEntryIds(ctx, req.(*GetRevisionsByEntryIdRequests))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetLatestRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetLatestRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.StoreService/GetLatestRevision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetLatestRevision(ctx, req.(*GetLatestRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_SnapDownload_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SnapDownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoreServiceServer).SnapDownload(m, &storeServiceSnapDownloadServer{stream})
}

type StoreService_SnapDownloadServer interface {
	Send(*SnapDownloadResponse) error
	grpc.ServerStream
}

type storeServiceSnapDownloadServer struct {
	grpc.ServerStream
}

func (x *storeServiceSnapDownloadServer) Send(m *SnapDownloadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StoreService_UnscannedUpload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StoreServiceServer).UnscannedUpload(&storeServiceUnscannedUploadServer{stream})
}

type StoreService_UnscannedUploadServer interface {
	SendAndClose(*UnscannedUploadCompleteResponse) error
	Recv() (*UnscannedUploadRequest, error)
	grpc.ServerStream
}

type storeServiceUnscannedUploadServer struct {
	grpc.ServerStream
}

func (x *storeServiceUnscannedUploadServer) SendAndClose(m *UnscannedUploadCompleteResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storeServiceUnscannedUploadServer) Recv() (*UnscannedUploadRequest, error) {
	m := new(UnscannedUploadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _StoreService_AddUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).AddUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.StoreService/AddUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).AddUpload(ctx, req.(*AddUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StoreService_ServiceDesc is the grpc.ServiceDesc for StoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "store.StoreService",
	HandlerType: (*StoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSnapName",
			Handler:    _StoreService_RegisterSnapName_Handler,
		},
		{
			MethodName: "GetRevisions",
			Handler:    _StoreService_GetRevisions_Handler,
		},
		{
			MethodName: "GetEntries",
			Handler:    _StoreService_GetEntries_Handler,
		},
		{
			MethodName: "GetEntriesByAccountId",
			Handler:    _StoreService_GetEntriesByAccountId_Handler,
		},
		{
			MethodName: "GetRevisionsByEntryIds",
			Handler:    _StoreService_GetRevisionsByEntryIds_Handler,
		},
		{
			MethodName: "GetLatestRevision",
			Handler:    _StoreService_GetLatestRevision_Handler,
		},
		{
			MethodName: "AddUpload",
			Handler:    _StoreService_AddUpload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SnapDownload",
			Handler:       _StoreService_SnapDownload_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UnscannedUpload",
			Handler:       _StoreService_UnscannedUpload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "store.proto",
}
