syntax = "proto3";

import "google/protobuf/timestamp.proto";

package store;
option go_package = "github.com/idlab-discover/kebeng/services/store/proto;store";

service StoreService {
    rpc UploadSnap(UploadSnapRequest) returns (UploadSnapResponse);
    rpc RegisterSnapName(RegisterSnapNameRequest) returns (RegisterSnapNameResponse);
    rpc GetRevisions(GetRevisionsRequest) returns (GetRevisionsResponse);
    rpc GetEntries(GetEntriesRequest) returns (GetEntriesResponse);
    rpc GetEntriesByAccountId(GetEntriesByAccountIdRequest) returns (GetEntriesResponse);
    rpc GetRevisionsByEntryIds(GetRevisionsByEntryIdRequests) returns (GetRevisionsByEntryIdResponses);
    rpc RefreshSnap(RefreshSnapRequest) returns (RefreshSnapResponse);
}

message UploadSnapRequest {
    string name = 1;
    string type = 2;
    string confinement = 3;
    string base = 4;
    bytes file = 5;
}

message UploadSnapResponse {
    string id = 1;
    string display_name = 2;
    repeated Error errors = 3;
}

message RegisterSnapNameRequest {
    string snap_name = 1;
    bool isPrivate = 2;
    string store = 3;
    bool dry_run = 4;
    string account_id = 5;
}

message RegisterSnapNameResponse {
    string id = 1;
    string snap_name = 2;
    repeated Error errors = 3;
}

message GetEntryRequest {
    optional string id = 1;
    optional string name = 2;
    repeated string preload_associations = 3;
}
// TODO: add snapComments
message GetEntryResponse {
    string id = 1;
    string snap_name = 2;
    optional string confinement = 3;
    optional string base = 4;
    optional string type = 5;
    optional bool private = 6;
    string publisher_id = 7;
    optional string status = 8;
    optional double price = 9;
    google.protobuf.Timestamp since = 10;
    optional string icon_url = 11;
    repeated GetRevisionResponse revisions = 12;
    repeated Error errors = 13;
}



message GetEntriesRequest {
    repeated GetEntryRequest entries = 1;
}

message GetEntriesResponse {
    repeated GetEntryResponse entries = 1;
    repeated Error errors = 2;
}

message GetRevisionRequest {
    string id = 1;
    string snap_name = 2;
    uint64 sequence = 3;
}

message GetRevisionResponse {
    string id = 1;
    string snap_name = 2;
    string build_assertion_filename = 3;
    uint64 sequence = 4;
    repeated string architectures = 5;
    string status = 6;
    string version = 7;
    repeated Error errors = 8;
}

message GetRevisionsRequest {
    repeated GetRevisionRequest revisions = 1;
}

message GetRevisionsResponse {
    repeated GetRevisionResponse revisions = 1;
    repeated Error errors = 2;
}

message Error {
    string message = 1;
    string code = 2;
}

message GetEntriesByAccountIdRequest {
    string account_id = 1;
}

message GetRevisionsByEntryIdRequest {
    string entry_id = 1;
}

message GetRevisionsByEntryIdRequests {
    repeated GetRevisionsByEntryIdRequest requests = 1;
}

message GetRevisionsByEntryIdResponse {
    string entry_id = 1;
    repeated GetRevisionResponse revisions = 2;
    repeated Error errors = 3;
}

message GetRevisionsByEntryIdResponses {
    repeated GetRevisionsByEntryIdResponse responses = 1;
    repeated Error errors = 2;
}

message RefreshSnapRequest {
    message Context {
        string snap_id = 1;
        string instance_key = 2;
        uint64 revision = 3;
        string tracking_channel = 4;
        message Epoch {
            repeated uint64 read = 1;
            repeated uint64 write = 2;
        }
        Epoch epoch = 5;
        google.protobuf.Timestamp refreshed_date = 6;
    }
    repeated Context context = 1;

    message Action {
        string action = 1;
        string instance_key = 2;
        string name = 3;
        string channel = 4;
        message Epoch {
            repeated uint64 read = 1;
            repeated uint64 write = 2;
        }
        Epoch epoch = 5;
    }
    repeated Action actions = 2;

    repeated string fields = 3;
}

message RefreshSnapResponse {
    repeated Error errors = 1;

    message Result {
        string result = 1;
        string instance_key = 2;
        string snap_id = 3;
        string name = 4;

        message Snap {
            repeated string architectures = 1;
            string snap_id = 2;
            string name = 3;

            message Download {
                string url = 1;
                string sha3_384 = 2;
                double size = 3;
            }
            Download download = 5;

            string version = 6;
            uint64 revision = 7;
            string confinement = 8;
            string type = 9;
        }
        Snap snap = 5;
    }
    repeated Result results = 2;
}

message SnapPushRequest {
    string snap_id = 1;
    string instance_key = 2;
    uint64 revision = 3;
    string track = 4;
    string channel = 5;
}