syntax = "proto3";

import "google/protobuf/timestamp.proto";

package store;
option go_package = "github.com/idlab-discover/kebeng/services/store/proto;store";

service StoreService {
    rpc UploadSnap(UploadSnapRequest) returns (UploadSnapResponse);
    rpc RegisterSnapName(RegisterSnapNameRequest) returns (RegisterSnapNameResponse);
    rpc GetRevisions(GetRevisionsRequest) returns (GetRevisionsResponse);
    rpc GetEntries(GetEntriesRequest) returns (GetEntriesResponse);
    rpc GetEntriesByAccountId(GetEntriesByAccountIdRequest) returns (GetEntriesResponse);
    rpc GetRevisionsByEntryIds(GetRevisionsByEntryIdRequests) returns (GetRevisionsByEntryIdResponses);
}

message UploadSnapRequest {
    string name = 1;
    string type = 2;
    string confinement = 3;
    string base = 4;
    bytes file = 5;
}

message UploadSnapResponse {
    string id = 1;
    string display_name = 2;
    repeated Error errors = 3;
}

message RegisterSnapNameRequest {
    string snap_name = 1;
    bool isPrivate = 2;
    string store = 3;
    bool dry_run = 4;
}

message RegisterSnapNameResponse {
    string id = 1;
    string snap_name = 2;
    repeated Error errors = 3;
}

message GetEntryRequest {
    string id = 1;
    string name = 2;
}

message GetEntryResponse {
    string id = 1;
    string snap_name = 2;
    string confinement = 3;
    string base = 4;
    string type = 5;
    bool private = 6;
    string publisher_id = 7;
    repeated Error errors = 8;
}

message GetEntriesRequest {
    repeated GetEntryRequest entries = 1;
}

message GetEntriesResponse {
    repeated GetEntryResponse entries = 1;
    repeated Error errors = 2;
}

message GetRevisionRequest {
    string id = 1;
    string snap_name = 2;
    uint64 sequence = 3;
}

message GetRevisionResponse {
    string id = 1;
    string snap_name = 2;
    uint64 sequence = 3;
    repeated string architectures = 4;
    string status = 5;
    string version = 6;
    google.protobuf.Timestamp since = 7;
    repeated Error errors = 8;
}

message GetRevisionsRequest {
    repeated GetRevisionRequest revisions = 1;
}

message GetRevisionsResponse {
    repeated GetRevisionResponse revisions = 1;
    repeated Error errors = 2;
}

message SnapBuildAssertionRequest {
    string snap_id = 1;
    string assertion = 2;
}

message SnapBuildAssertionResponse {
    string authority_id = 1;
    string grade = 2;
    string sign_key_sha3_384 = 3;
    string snap_id = 4;
    string snap_sha3_384 = 5;
    string snap_size = 6;
    string timestamp = 7;
    string revision = 8;
    string type = 9;
    repeated Error errors = 10;
}

message Error {
    string message = 1;
    string code = 2;
}

message GetEntriesByAccountIdRequest {
    string account_id = 1;
}

message GetRevisionsByEntryIdRequest {
    string entry_id = 1;
}

message GetRevisionsByEntryIdRequests {
    repeated GetRevisionsByEntryIdRequest requests = 1;
}

message GetRevisionsByEntryIdResponse {
    string entry_id = 1;
    repeated GetRevisionResponse revisions = 2;
    repeated Error errors = 3;
}

message GetRevisionsByEntryIdResponses {
    repeated GetRevisionsByEntryIdResponse responses = 1;
    repeated Error errors = 2;
}
