// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: services/store/proto/store.proto

package store

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoreService_RegisterSnapName_FullMethodName                   = "/store.StoreService/RegisterSnapName"
	StoreService_GetRevisions_FullMethodName                       = "/store.StoreService/GetRevisions"
	StoreService_GetEntries_FullMethodName                         = "/store.StoreService/GetEntries"
	StoreService_GetEntryById_FullMethodName                       = "/store.StoreService/GetEntryById"
	StoreService_GetEntriesByAccountId_FullMethodName              = "/store.StoreService/GetEntriesByAccountId"
	StoreService_GetEntriesByQuery_FullMethodName                  = "/store.StoreService/GetEntriesByQuery"
	StoreService_GetRevisionsByEntryIds_FullMethodName             = "/store.StoreService/GetRevisionsByEntryIds"
	StoreService_GetLatestRevisionBeforeDateById_FullMethodName    = "/store.StoreService/GetLatestRevisionBeforeDateById"
	StoreService_GetLatestRevisionByTrackAndChannel_FullMethodName = "/store.StoreService/GetLatestRevisionByTrackAndChannel"
	StoreService_SnapDownload_FullMethodName                       = "/store.StoreService/SnapDownload"
	StoreService_UnscannedUpload_FullMethodName                    = "/store.StoreService/UnscannedUpload"
	StoreService_AddUpload_FullMethodName                          = "/store.StoreService/AddUpload"
	StoreService_GetUploadStatus_FullMethodName                    = "/store.StoreService/GetUploadStatus"
	StoreService_AddRevision_FullMethodName                        = "/store.StoreService/AddRevision"
	StoreService_GetObjectCustomMetadata_FullMethodName            = "/store.StoreService/GetObjectCustomMetadata"
	StoreService_UpdateUploadStatus_FullMethodName                 = "/store.StoreService/UpdateUploadStatus"
	StoreService_UpdateSnapEntryWithMetadata_FullMethodName        = "/store.StoreService/UpdateSnapEntryWithMetadata"
)

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoreServiceClient interface {
	RegisterSnapName(ctx context.Context, in *RegisterSnapNameRequest, opts ...grpc.CallOption) (*RegisterSnapNameResponse, error)
	GetRevisions(ctx context.Context, in *GetRevisionsRequest, opts ...grpc.CallOption) (*GetRevisionsResponse, error)
	GetEntries(ctx context.Context, in *GetEntriesRequest, opts ...grpc.CallOption) (*GetEntriesResponse, error)
	GetEntryById(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*GetEntryResponse, error)
	GetEntriesByAccountId(ctx context.Context, in *GetEntriesByAccountIdRequest, opts ...grpc.CallOption) (*GetEntriesResponse, error)
	GetEntriesByQuery(ctx context.Context, in *GetEntriesByQueryRequest, opts ...grpc.CallOption) (*GetEntriesResponse, error)
	GetRevisionsByEntryIds(ctx context.Context, in *GetRevisionsByEntryIdRequests, opts ...grpc.CallOption) (*GetRevisionsByEntryIdResponses, error)
	GetLatestRevisionBeforeDateById(ctx context.Context, in *GetLatestRevisionBeforeDateByIdRequest, opts ...grpc.CallOption) (*GetRevisionResponse, error)
	GetLatestRevisionByTrackAndChannel(ctx context.Context, in *GetLatestRevisionRequest, opts ...grpc.CallOption) (*GetRevisionResponse, error)
	SnapDownload(ctx context.Context, in *SnapDownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapDownloadResponse], error)
	UnscannedUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UnscannedUploadRequest, UnscannedUploadCompleteResponse], error)
	AddUpload(ctx context.Context, in *AddUploadRequest, opts ...grpc.CallOption) (*AddUploadResponse, error)
	GetUploadStatus(ctx context.Context, in *GetUploadStatusRequest, opts ...grpc.CallOption) (*GetUploadStatusResponse, error)
	AddRevision(ctx context.Context, in *AddRevisionRequest, opts ...grpc.CallOption) (*AddRevisionResponse, error)
	GetObjectCustomMetadata(ctx context.Context, in *GetObjectCustomMetadataRequest, opts ...grpc.CallOption) (*GetObjectCustomMetadataResponse, error)
	UpdateUploadStatus(ctx context.Context, in *UpdateUploadStatusRequest, opts ...grpc.CallOption) (*UpdateUploadStatusResponse, error)
	UpdateSnapEntryWithMetadata(ctx context.Context, in *UpdateSnapEntryWithMetadataRequest, opts ...grpc.CallOption) (*UpdateEntryResponse, error)
}

type storeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreServiceClient(cc grpc.ClientConnInterface) StoreServiceClient {
	return &storeServiceClient{cc}
}

func (c *storeServiceClient) RegisterSnapName(ctx context.Context, in *RegisterSnapNameRequest, opts ...grpc.CallOption) (*RegisterSnapNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterSnapNameResponse)
	err := c.cc.Invoke(ctx, StoreService_RegisterSnapName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetRevisions(ctx context.Context, in *GetRevisionsRequest, opts ...grpc.CallOption) (*GetRevisionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRevisionsResponse)
	err := c.cc.Invoke(ctx, StoreService_GetRevisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetEntries(ctx context.Context, in *GetEntriesRequest, opts ...grpc.CallOption) (*GetEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntriesResponse)
	err := c.cc.Invoke(ctx, StoreService_GetEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetEntryById(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*GetEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntryResponse)
	err := c.cc.Invoke(ctx, StoreService_GetEntryById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetEntriesByAccountId(ctx context.Context, in *GetEntriesByAccountIdRequest, opts ...grpc.CallOption) (*GetEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntriesResponse)
	err := c.cc.Invoke(ctx, StoreService_GetEntriesByAccountId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetEntriesByQuery(ctx context.Context, in *GetEntriesByQueryRequest, opts ...grpc.CallOption) (*GetEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntriesResponse)
	err := c.cc.Invoke(ctx, StoreService_GetEntriesByQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetRevisionsByEntryIds(ctx context.Context, in *GetRevisionsByEntryIdRequests, opts ...grpc.CallOption) (*GetRevisionsByEntryIdResponses, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRevisionsByEntryIdResponses)
	err := c.cc.Invoke(ctx, StoreService_GetRevisionsByEntryIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetLatestRevisionBeforeDateById(ctx context.Context, in *GetLatestRevisionBeforeDateByIdRequest, opts ...grpc.CallOption) (*GetRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRevisionResponse)
	err := c.cc.Invoke(ctx, StoreService_GetLatestRevisionBeforeDateById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetLatestRevisionByTrackAndChannel(ctx context.Context, in *GetLatestRevisionRequest, opts ...grpc.CallOption) (*GetRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRevisionResponse)
	err := c.cc.Invoke(ctx, StoreService_GetLatestRevisionByTrackAndChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) SnapDownload(ctx context.Context, in *SnapDownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapDownloadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StoreService_ServiceDesc.Streams[0], StoreService_SnapDownload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SnapDownloadRequest, SnapDownloadResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoreService_SnapDownloadClient = grpc.ServerStreamingClient[SnapDownloadResponse]

func (c *storeServiceClient) UnscannedUpload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UnscannedUploadRequest, UnscannedUploadCompleteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StoreService_ServiceDesc.Streams[1], StoreService_UnscannedUpload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UnscannedUploadRequest, UnscannedUploadCompleteResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoreService_UnscannedUploadClient = grpc.ClientStreamingClient[UnscannedUploadRequest, UnscannedUploadCompleteResponse]

func (c *storeServiceClient) AddUpload(ctx context.Context, in *AddUploadRequest, opts ...grpc.CallOption) (*AddUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUploadResponse)
	err := c.cc.Invoke(ctx, StoreService_AddUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetUploadStatus(ctx context.Context, in *GetUploadStatusRequest, opts ...grpc.CallOption) (*GetUploadStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUploadStatusResponse)
	err := c.cc.Invoke(ctx, StoreService_GetUploadStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) AddRevision(ctx context.Context, in *AddRevisionRequest, opts ...grpc.CallOption) (*AddRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRevisionResponse)
	err := c.cc.Invoke(ctx, StoreService_AddRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetObjectCustomMetadata(ctx context.Context, in *GetObjectCustomMetadataRequest, opts ...grpc.CallOption) (*GetObjectCustomMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObjectCustomMetadataResponse)
	err := c.cc.Invoke(ctx, StoreService_GetObjectCustomMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) UpdateUploadStatus(ctx context.Context, in *UpdateUploadStatusRequest, opts ...grpc.CallOption) (*UpdateUploadStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUploadStatusResponse)
	err := c.cc.Invoke(ctx, StoreService_UpdateUploadStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) UpdateSnapEntryWithMetadata(ctx context.Context, in *UpdateSnapEntryWithMetadataRequest, opts ...grpc.CallOption) (*UpdateEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEntryResponse)
	err := c.cc.Invoke(ctx, StoreService_UpdateSnapEntryWithMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServiceServer is the server API for StoreService service.
// All implementations must embed UnimplementedStoreServiceServer
// for forward compatibility.
type StoreServiceServer interface {
	RegisterSnapName(context.Context, *RegisterSnapNameRequest) (*RegisterSnapNameResponse, error)
	GetRevisions(context.Context, *GetRevisionsRequest) (*GetRevisionsResponse, error)
	GetEntries(context.Context, *GetEntriesRequest) (*GetEntriesResponse, error)
	GetEntryById(context.Context, *GetEntryRequest) (*GetEntryResponse, error)
	GetEntriesByAccountId(context.Context, *GetEntriesByAccountIdRequest) (*GetEntriesResponse, error)
	GetEntriesByQuery(context.Context, *GetEntriesByQueryRequest) (*GetEntriesResponse, error)
	GetRevisionsByEntryIds(context.Context, *GetRevisionsByEntryIdRequests) (*GetRevisionsByEntryIdResponses, error)
	GetLatestRevisionBeforeDateById(context.Context, *GetLatestRevisionBeforeDateByIdRequest) (*GetRevisionResponse, error)
	GetLatestRevisionByTrackAndChannel(context.Context, *GetLatestRevisionRequest) (*GetRevisionResponse, error)
	SnapDownload(*SnapDownloadRequest, grpc.ServerStreamingServer[SnapDownloadResponse]) error
	UnscannedUpload(grpc.ClientStreamingServer[UnscannedUploadRequest, UnscannedUploadCompleteResponse]) error
	AddUpload(context.Context, *AddUploadRequest) (*AddUploadResponse, error)
	GetUploadStatus(context.Context, *GetUploadStatusRequest) (*GetUploadStatusResponse, error)
	AddRevision(context.Context, *AddRevisionRequest) (*AddRevisionResponse, error)
	GetObjectCustomMetadata(context.Context, *GetObjectCustomMetadataRequest) (*GetObjectCustomMetadataResponse, error)
	UpdateUploadStatus(context.Context, *UpdateUploadStatusRequest) (*UpdateUploadStatusResponse, error)
	UpdateSnapEntryWithMetadata(context.Context, *UpdateSnapEntryWithMetadataRequest) (*UpdateEntryResponse, error)
	mustEmbedUnimplementedStoreServiceServer()
}

// UnimplementedStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoreServiceServer struct{}

func (UnimplementedStoreServiceServer) RegisterSnapName(context.Context, *RegisterSnapNameRequest) (*RegisterSnapNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterSnapName not implemented")
}
func (UnimplementedStoreServiceServer) GetRevisions(context.Context, *GetRevisionsRequest) (*GetRevisionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRevisions not implemented")
}
func (UnimplementedStoreServiceServer) GetEntries(context.Context, *GetEntriesRequest) (*GetEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntries not implemented")
}
func (UnimplementedStoreServiceServer) GetEntryById(context.Context, *GetEntryRequest) (*GetEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntryById not implemented")
}
func (UnimplementedStoreServiceServer) GetEntriesByAccountId(context.Context, *GetEntriesByAccountIdRequest) (*GetEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntriesByAccountId not implemented")
}
func (UnimplementedStoreServiceServer) GetEntriesByQuery(context.Context, *GetEntriesByQueryRequest) (*GetEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntriesByQuery not implemented")
}
func (UnimplementedStoreServiceServer) GetRevisionsByEntryIds(context.Context, *GetRevisionsByEntryIdRequests) (*GetRevisionsByEntryIdResponses, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRevisionsByEntryIds not implemented")
}
func (UnimplementedStoreServiceServer) GetLatestRevisionBeforeDateById(context.Context, *GetLatestRevisionBeforeDateByIdRequest) (*GetRevisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestRevisionBeforeDateById not implemented")
}
func (UnimplementedStoreServiceServer) GetLatestRevisionByTrackAndChannel(context.Context, *GetLatestRevisionRequest) (*GetRevisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestRevisionByTrackAndChannel not implemented")
}
func (UnimplementedStoreServiceServer) SnapDownload(*SnapDownloadRequest, grpc.ServerStreamingServer[SnapDownloadResponse]) error {
	return status.Error(codes.Unimplemented, "method SnapDownload not implemented")
}
func (UnimplementedStoreServiceServer) UnscannedUpload(grpc.ClientStreamingServer[UnscannedUploadRequest, UnscannedUploadCompleteResponse]) error {
	return status.Error(codes.Unimplemented, "method UnscannedUpload not implemented")
}
func (UnimplementedStoreServiceServer) AddUpload(context.Context, *AddUploadRequest) (*AddUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUpload not implemented")
}
func (UnimplementedStoreServiceServer) GetUploadStatus(context.Context, *GetUploadStatusRequest) (*GetUploadStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUploadStatus not implemented")
}
func (UnimplementedStoreServiceServer) AddRevision(context.Context, *AddRevisionRequest) (*AddRevisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRevision not implemented")
}
func (UnimplementedStoreServiceServer) GetObjectCustomMetadata(context.Context, *GetObjectCustomMetadataRequest) (*GetObjectCustomMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObjectCustomMetadata not implemented")
}
func (UnimplementedStoreServiceServer) UpdateUploadStatus(context.Context, *UpdateUploadStatusRequest) (*UpdateUploadStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUploadStatus not implemented")
}
func (UnimplementedStoreServiceServer) UpdateSnapEntryWithMetadata(context.Context, *UpdateSnapEntryWithMetadataRequest) (*UpdateEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSnapEntryWithMetadata not implemented")
}
func (UnimplementedStoreServiceServer) mustEmbedUnimplementedStoreServiceServer() {}
func (UnimplementedStoreServiceServer) testEmbeddedByValue()                      {}

// UnsafeStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreServiceServer will
// result in compilation errors.
type UnsafeStoreServiceServer interface {
	mustEmbedUnimplementedStoreServiceServer()
}

func RegisterStoreServiceServer(s grpc.ServiceRegistrar, srv StoreServiceServer) {
	// If the following call panics, it indicates UnimplementedStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoreService_ServiceDesc, srv)
}

func _StoreService_RegisterSnapName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSnapNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).RegisterSnapName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_RegisterSnapName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).RegisterSnapName(ctx, req.(*RegisterSnapNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetRevisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRevisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetRevisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetRevisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetRevisions(ctx, req.(*GetRevisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetEntries(ctx, req.(*GetEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetEntryById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetEntryById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetEntryById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetEntryById(ctx, req.(*GetEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetEntriesByAccountId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntriesByAccountIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetEntriesByAccountId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetEntriesByAccountId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetEntriesByAccountId(ctx, req.(*GetEntriesByAccountIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetEntriesByQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntriesByQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetEntriesByQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetEntriesByQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetEntriesByQuery(ctx, req.(*GetEntriesByQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetRevisionsByEntryIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRevisionsByEntryIdRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetRevisionsByEntryIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetRevisionsByEntryIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetRevisionsByEntryIds(ctx, req.(*GetRevisionsByEntryIdRequests))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetLatestRevisionBeforeDateById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestRevisionBeforeDateByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetLatestRevisionBeforeDateById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetLatestRevisionBeforeDateById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetLatestRevisionBeforeDateById(ctx, req.(*GetLatestRevisionBeforeDateByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetLatestRevisionByTrackAndChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetLatestRevisionByTrackAndChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetLatestRevisionByTrackAndChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetLatestRevisionByTrackAndChannel(ctx, req.(*GetLatestRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_SnapDownload_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SnapDownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StoreServiceServer).SnapDownload(m, &grpc.GenericServerStream[SnapDownloadRequest, SnapDownloadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoreService_SnapDownloadServer = grpc.ServerStreamingServer[SnapDownloadResponse]

func _StoreService_UnscannedUpload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StoreServiceServer).UnscannedUpload(&grpc.GenericServerStream[UnscannedUploadRequest, UnscannedUploadCompleteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StoreService_UnscannedUploadServer = grpc.ClientStreamingServer[UnscannedUploadRequest, UnscannedUploadCompleteResponse]

func _StoreService_AddUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).AddUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_AddUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).AddUpload(ctx, req.(*AddUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetUploadStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetUploadStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetUploadStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetUploadStatus(ctx, req.(*GetUploadStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_AddRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).AddRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_AddRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).AddRevision(ctx, req.(*AddRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetObjectCustomMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectCustomMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetObjectCustomMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetObjectCustomMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetObjectCustomMetadata(ctx, req.(*GetObjectCustomMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_UpdateUploadStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUploadStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).UpdateUploadStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_UpdateUploadStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).UpdateUploadStatus(ctx, req.(*UpdateUploadStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_UpdateSnapEntryWithMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSnapEntryWithMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).UpdateSnapEntryWithMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_UpdateSnapEntryWithMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).UpdateSnapEntryWithMetadata(ctx, req.(*UpdateSnapEntryWithMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StoreService_ServiceDesc is the grpc.ServiceDesc for StoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "store.StoreService",
	HandlerType: (*StoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSnapName",
			Handler:    _StoreService_RegisterSnapName_Handler,
		},
		{
			MethodName: "GetRevisions",
			Handler:    _StoreService_GetRevisions_Handler,
		},
		{
			MethodName: "GetEntries",
			Handler:    _StoreService_GetEntries_Handler,
		},
		{
			MethodName: "GetEntryById",
			Handler:    _StoreService_GetEntryById_Handler,
		},
		{
			MethodName: "GetEntriesByAccountId",
			Handler:    _StoreService_GetEntriesByAccountId_Handler,
		},
		{
			MethodName: "GetEntriesByQuery",
			Handler:    _StoreService_GetEntriesByQuery_Handler,
		},
		{
			MethodName: "GetRevisionsByEntryIds",
			Handler:    _StoreService_GetRevisionsByEntryIds_Handler,
		},
		{
			MethodName: "GetLatestRevisionBeforeDateById",
			Handler:    _StoreService_GetLatestRevisionBeforeDateById_Handler,
		},
		{
			MethodName: "GetLatestRevisionByTrackAndChannel",
			Handler:    _StoreService_GetLatestRevisionByTrackAndChannel_Handler,
		},
		{
			MethodName: "AddUpload",
			Handler:    _StoreService_AddUpload_Handler,
		},
		{
			MethodName: "GetUploadStatus",
			Handler:    _StoreService_GetUploadStatus_Handler,
		},
		{
			MethodName: "AddRevision",
			Handler:    _StoreService_AddRevision_Handler,
		},
		{
			MethodName: "GetObjectCustomMetadata",
			Handler:    _StoreService_GetObjectCustomMetadata_Handler,
		},
		{
			MethodName: "UpdateUploadStatus",
			Handler:    _StoreService_UpdateUploadStatus_Handler,
		},
		{
			MethodName: "UpdateSnapEntryWithMetadata",
			Handler:    _StoreService_UpdateSnapEntryWithMetadata_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SnapDownload",
			Handler:       _StoreService_SnapDownload_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UnscannedUpload",
			Handler:       _StoreService_UnscannedUpload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "services/store/proto/store.proto",
}
