name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Build Account service
      working-directory: ./services/account
      run: go build -v ./

    - name: Build Assertion service
      working-directory: ./services/assertion
      run: go build -v ./

    - name: Build Gateway service
      working-directory: ./services/gateway
      run: go build -v ./

    - name: Build Store service
      working-directory: ./services/store
      run: go build -v ./

    - name: Test Account service
      working-directory: ./services/account
      run: go test -v ./

    - name: Test Assertion service
      working-directory: ./services/assertion
      run: go test -v ./

    - name: Test Gateway service
      working-directory: ./services/gateway
      run: go test -v ./

    - name: Test Store service
      working-directory: ./services/store
      run: go test -v ./
