name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Build services
      working-directory: ./services
      run: |
        go build -v ./account
        go build -v ./assertion
        go build -v ./gateway
        go build -v ./store

    - name: Test
      working-directory: ./services
      run: go test -v ./account ./assertion ./gateway ./store
