syntax = "proto3";

package account;
option go_package = "github.com/idlab-discover/kebeng/services/account/proto;account";

service AccountService {
    rpc CreateAccount(CreateAccountRequest) returns (Account);
    rpc UpdateAccount(UpdateAccountRequest) returns (Account);
    rpc DeleteAccount(DeleteAccountRequest) returns (DeleteAccountResponse);
    rpc GetAccountByEmail(GetAccountByEmailRequest) returns (Account);
    rpc GetAccountByID(GetAccountByIDRequest) returns (Account);
    rpc GetAccountByUsername(GetAccountByUsernameRequest) returns (Account);

    rpc AddKey(AddKeyRequest) returns (Key);
    rpc GetKeyBySHA3384(GetKeyBySHA3384Request) returns (Key);

    rpc GenerateMacaroon(GenerateMacaroonRequest) returns (Macaroon);
}

message Account {
    string id = 1;
    string display_name = 2;
    string username = 3;
    string email = 4;
}

message CreateAccountRequest {
    string display_name = 1;
    string username = 2;
    string email = 3;
}

message UpdateAccountRequest {
    string id = 1;
    string display_name = 2;
    string username = 3;
    string email = 4;
}

message DeleteAccountRequest {
    string id = 1;
}

message DeleteAccountResponse {
    bool success = 1;
}

message GetAccountByEmailRequest {
    string email = 1;
}

message GetAccountByIDRequest {
    string id = 1;
}

message GetAccountByUsernameRequest {
    string username = 1;
}

message Key {
    string name = 1;
    string sha3384 = 2;
    string encoded_public_key = 3;
}

message AddKeyRequest {
    string account_email = 1;
    string key_name = 2;
    string sha3384 = 3;
    string encoded_public_key = 4;
}

message GetKeyBySHA3384Request {
    string sha3384 = 1;
}

// ACL is the access control list that will be embedded in the macaroon
message GenerateMacaroonRequest {
    // The ACL string to be embedded as a first-party caveat
    string acl = 1;
}

message Macaroon {
    // The serialized macaroon string
    string macaroon = 1;
}
