syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "common/cerror/proto/error.proto";

package account;
option go_package = "github.com/idlab-discover/kebeng/services/account/proto;account";

service AccountService {
    rpc AddAccount(AddAccountRequest) returns (AccountResponse);
    rpc UpdateAccount(UpdateAccountRequest) returns (AccountResponse);
    rpc DeleteAccount(DeleteAccountRequest) returns (DeleteAccountResponse);
    rpc GetAccountByEmail(GetAccountByEmailRequest) returns (AccountResponse);
    rpc GetAccountByID(GetAccountByIDRequest) returns (AccountResponse);
    rpc GetAccountsByIds(GetAccountsByIdsRequest) returns (GetAccountsByIdsResponse);
    rpc GetAccountByUsername(GetAccountByUsernameRequest) returns (AccountResponse);
    rpc AddKey(AddKeyRequest) returns (KeyResponse);
    rpc GetKeyBySHA3384(GetKeyBySHA3384Request) returns (KeyResponse);
    rpc GetKeysByAccountId(GetKeysByAccountIdRequest) returns (KeysResponse);
    rpc PatchAccountByEmail(PatchAccountByEmailRequest) returns (PatchAccountByEmailResponse);
}

message AccountResponse {
    string id = 1;
    string display_name = 2;
    string username = 3;
    string email = 4;
    optional string validation = 5;
    repeated proto.Error errors = 6;
}

message KeysResponse {
    repeated KeyResponse keys = 1;
    repeated proto.Error errors = 2;
}

message AddAccountRequest {
    string display_name = 1;
    string username = 2;
    string email = 3;
    string hashed_password = 4;
}

message UpdateAccountRequest {
    string id = 1;
    string display_name = 2;
    string username = 3;
    string email = 4;
}

message DeleteAccountRequest {
    string id = 1;
}

message DeleteAccountResponse {
    bool success = 1;
    repeated proto.Error errors = 2;
}

message GetAccountByEmailRequest {
    string email = 1;
}

message GetAccountByIDRequest {
    string id = 1;
}

message GetAccountByUsernameRequest {
    string username = 1;
}

message KeyResponse {
    string id = 1;
    string name = 2;
    string sha3384 = 3;
    string encoded_public_key = 4;
    // Use google.protobuf.Timestamp for fields that are pointers in Go.
    optional google.protobuf.Timestamp since = 5;
    optional google.protobuf.Timestamp until = 6;   
    repeated proto.Error errors = 7;
}

message AddKeyRequest {
    string account_email = 1;
    string key_name = 2;
    string sha3384 = 3;
    string encoded_public_key = 4;
}

message GetKeyBySHA3384Request {
    string sha3384 = 1;
}

message GetKeysByAccountIdRequest {
    string account_id = 1;
}

message GetAccountsByIdsRequest {
    repeated string ids = 1;
}

message GetAccountsByIdsResponse {
    repeated AccountResponse accounts = 1;
    repeated proto.Error errors = 2;
}

message PatchAccountByEmailRequest {
    string email = 1;
    string username = 2;
}

message PatchAccountByEmailResponse {
    string short_namespace = 1; // this is just the username
    repeated proto.Error errors = 2;
}
